# =========================================================================
# KRIDAZ MIGRATION AUDIT TOOL
# Auto-generated by Antigravity to verify transition checklist integrity.
# =========================================================================

$results = [ordered]@{
    # Phase 1: Infrastructure and Config Hardening
    "1D_Alias_app"             = if (Select-String -Path "vite.config.js" -Pattern '"@app"') { "✅ DONE" } else { "❌ MISSING" }
    "1E_Deleted_check_imports" = if (-not (Test-Path "src/check_imports.cjs")) { "✅ DONE" } else { "🗑️ NOT DELETED" }
    "1F_Fix_sentry_rate"       = if (Select-String -Path "src/main.jsx" -Pattern "tracesSampleRate: 0.1") { "✅ DONE" } else { "❌ MISSING" }
    "1F_Fix_console_log"       = if (-not (Select-String -Path "src/main.jsx" -Pattern "console.log.*react mount")) { "✅ DONE" } else { "⚠️ PARTIAL" }
    "1F_Fix_yup_removed"       = if (-not (Select-String -Path "src/shared/hooks/useBecomeOwner.jsx" -Pattern "yup")) { "✅ DONE" } else { "⚠️ PARTIAL" }

    # Phase 2: Miscellaneous Migration
    "2K_Misc_Profile"          = if (Test-Path "src/shared/components/shared/DashboardProfile.jsx") { "✅ DONE" } else { "❌ MISSING" }

    # Phase 4: TypeScript Contracts and Adapters
    "4A_Contract_User"         = if (Test-Path "src/contracts/user.contract.ts") { "✅ DONE" } else { "❌ MISSING" }
    "4B_Mapper_Auth"           = if (Test-Path "src/features/auth/mappers/auth.mapper.ts") { "✅ DONE" } else { "❌ MISSING" }

    # Phase 5: Architecture Boundaries and SEO Optimization
    "5A_Layout_Admin_Boundary" = if (Select-String -Path "src/shared/layouts/AdminLayout.jsx" -Pattern "ErrorBoundary") { "✅ DONE" } else { "❌ MISSING" }
    "5A_App_Boundary"          = if (Select-String -Path "src/app/App.jsx" -Pattern "ErrorBoundary") { "✅ DONE" } else { "❌ MISSING" }
    "5B_SEO_HelmetProvider"    = if (Select-String -Path "src/main.jsx" -Pattern "HelmetProvider") { "✅ DONE" } else { "❌ MISSING" }
    "5B_SEO_LoginMeta"         = if (Select-String -Path "src/features/auth/pages/Login.jsx" -Pattern "Helmet") { "✅ DONE" } else { "❌ MISSING" }
}

Write-Host "`n==================================================" -ForegroundColor Green
Write-Host "        KRIDAZ TRANSITION CHECKLIST AUDIT         " -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green

$total = $results.Count
$done = 0

foreach ($key in $results.Keys) {
    $status = $results[$key]
    if ($status -eq "✅ DONE") {
        $done++
        Write-Host "  $key".PadRight(30) + ": [ $status ]" -ForegroundColor Green
    } else {
        Write-Host "  $key".PadRight(30) + ": [ $status ]" -ForegroundColor Red
    }
}

$percentage = [Math]::Round(($done / $total) * 100)
Write-Host "=================================================="
Write-Host "  COMPLETION SCORE: $percentage% ($done / $total files verified)" -ForegroundColor Cyan
Write-Host "==================================================`n"
